### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by SaiSakhamuri** [facebookresearch/3D-Vision-and-Touch#4]
import models
import utils
import data_loaders

I am getting below error in recon.py.
Import "models" could not be resolvedPyright(reportMissingImports)
Could you please help me with this error

**Comment by EdwardSmith1884** [comment]
Hi, I am working on double checking everything and will push a new version of the code tomorrow which can work with more recent versions of pytorch and cuda. In the mean time can you let me know what environment you are using?

**Comment by SaiSakhamuri** [comment]
Hi,

I am using google collab environment. The steps I followed are as below.
1. I have cloned using !git clone
https://github.com/facebookresearch/3D-Vision-and-Touch.git
2. pip install torch==1.4.0
3. import os
os.chdir('/content/3D-Vision-and-Touch')
4. !bash download_data.sh
5. !cd touch_charts
6. !python touch_charts/recon.py --exp_type 1 --exp_id 1  after this step I
am getting below error.
*Traceback (most recent call last): File "touch_charts/recon.py", line 18,
in <module> import utils ModuleNotFoundError: No module named 'utils'* All
the import statements of .py files in other files also showing errors.
Thanks,
Sai

**Comment by EdwardSmith1884** [comment]
Hi, so I updated the code to use pytorch3D , meaning you can use much more recent version of pytorch and cuda. I would recommend pulling the new code, following the install instructions from scratch and seeing if this solves the issue. If not let me know and I will see what I can do.

**Comment by SaiSakhamuri** [comment]
Still getting same issues. When  there are .py modules imported in other .py models it shows errors. Not sure, Whether I am missing anything to set the path. Please find the attached screenshots.
When I execute the command **!python recon.py --exp_type test --exp_id 1** 

Traceback (most recent call last):
  File "recon.py", line 18, in <module>
    import utils
  File "../utils.py", line 11, in <module>
    from pytorch3d.loss im
![Uploading Screen Shot 2022-04-10 at 1.59.35 PM.png…]()
port chamfer_distance as cuda_cd
ModuleNotFoundError: No module named 'pytorch3d'
<img width="1440" alt="Screen Shot 2022-04-10 at 1 59 35 PM" src="https://user-images.githubusercontent.com/93230760/162635540-3764a6bc-56dc-4d1
<img width="1440" alt="Screen Shot 2022-04-10 at 1 59 53 PM" src="https://user-images.githubusercontent.com/93230760/162635569-a58e65b9-e8dd-44fb-ba3e-81e4d4cdc1bb.png">

<img width="1388" alt="Screen Shot 2022-04-10 at 1 59 17 PM" src="https://user-images.githubusercontent.com/93230760/162635564-5b6db1ab-4dc8-4e71-b013-ea6775d825ae.png">
9-af73-c495139288e3.png">
<img width="1440" alt="Screen Shot 2022-04-10 at 1 59 35 PM" src="https://user-images.githubusercontent.com/93230760/162635547-ff963471-3e64-4077-97dc-6ce04a7987d5.png">

**Comment by EdwardSmith1884** [comment]
Hi, so it looks like the path issue has been resolved as it reaches utils.py . Now it looks like you have not install pytorch3D. Try installing it and see if this resolves the problem.
